kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
  proxy-connect-timeout : "30s"
  proxy-read-timeout : "10s"
  client_max_body_size: "100m"
  server_tokens: "off"
  lb-method: "round_robin"
  #proxy-protocol: "True"
  # real-ip-header: "proxy_protocol"
  #set-real-ip-from: "192.168.1.4/16"

#Used for global Nginx-Ingress fonfigurations. For ingress specific configs, annotations must be used.