---
- hosts: kubernetes-master
  vars_files:
    - vars.yaml
  become: true

  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Create a login user
    user:
     name: "{{ user_name }}"
     password: "{{ user_password }}"
     groups:
      - docker
      - sudo
     state: present
     shell: /bin/bash       # Defaults to /bin/bash
     system: no             # Defaults to no
     createhome: yes        # Defaults to yes
     home: /home/{{ user_name }}  # Defaults to /home/<username>

  - name: Enabling K8s to see bridged traffic
    shell:
      cmd: |
        cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
        net.bridge.bridge-nf-call-ip6tables=1
        net.bridge.bridge-nf-call-iptables=1
        EOF
        sysctl --system

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --pod-network-cidr=10.244.0.0/16


  - name: Create .kube folder
    become: false
    file:
      path: /home/{{ user_name }}/.kube
      state: directory

  - name: Copy admin.conf file
    copy: remote_src=true src=/etc/kubernetes/admin.conf dest=/home/{{ user_name }}/.kube/config

  - name: Change admin.conf owner
    file:
      path: /home/{{ user_name }}/.kube
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: Install Flunner pod network
    become: true
    become_user: "{{ user_name }}"
    #command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: kubernetes_join_command

  - name: Copy join command to local file
    copy: 
      dest: "cluster_join_command" 
      content: "{{ kubernetes_join_command.stdout_lines[0] }}"
    become: false
    delegate_to: localhost

  handlers:
    - name: docker status
      service: name=docker state=started
